### ISSUE TITLE
Set up scalaPy HelloWorld code and run into "Unable to load library python3"

### ISSUE THREAD

**Issue by LizzyMiao** [scalapy/scalapy#352]
hi I follow the doc: https://scalapy.dev/docs/  and perform below operation in one of my project in Intellij
1. add `libraryDependencies += "me.shadaj" %% "scalapy-core" % "0.5.2"` into build.sbt
2. add below code into build.sbt at the button
```
fork := true
//import ai.kien.python.Python
val python1 = ai.kien.python.Python()
lazy val javaOpts = python1.scalapyProperties.get.map {
  case (k, v) => s"""-D$k=$v"""
}.toSeq
ThisBuild / javaOptions ++= javaOpts
```
3. add  `libraryDependencies += "ai.kien" %% "python-native-libs" % "0.2.4"` into plugins.sbt

Then I write a very simple scalaPy code like below
```
import me.shadaj.scalapy.py
import me.shadaj.scalapy.py.SeqConverters

object PythonTest {
  def main(args: Array[String]): Unit = {
    val mypy = py.module("mypy")
    print("hello")
  }
}
```
Then run with IDE run button, it says below error:
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'python3':
dlopen(libpython3.dylib, 9): image not found
dlopen(libpython3.dylib, 9): image not found
dlopen(/Users/limiao/Library/Frameworks/python3.framework/python3, 9): image not found
dlopen(/Library/Frameworks/python3.framework/python3, 9): image not found
dlopen(/System/Library/Frameworks/python3.framework/python3, 9): image not found
Native library (darwin-x86-64/libpython3.dylib) not found in resource path

I have a python installed in my local machine and it is Python 3.9.7 located in this place /usr/bin/python

**Comment by kiendang** [comment]
Could you try passing the path to the Python executable
```scala
val python1 = ai.kien.python.Python("/usr/bin/python")
```

**Comment by LizzyMiao** [comment]
I tried with my python of my anaconda env, 

`val python1 = ai.kien.python.Python("/Users/XXX-userName/opt/anaconda3/envs/self_test/bin")`

1. stil has errors, I pasted detailed error below...  
2. doe this Python executable path is a must? If so how does this integrate with spark? If we installed python in our yarn cluster nodes, how would spark executor got access to this directory in runtime?

Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'python3':
dlopen(libpython3.dylib, 9): image not found
dlopen(libpython3.dylib, 9): image not found
dlopen(/Users/XXX-userName/Library/Frameworks/python3.framework/python3, 9): image not found
dlopen(/Library/Frameworks/python3.framework/python3, 9): image not found
dlopen(/System/Library/Frameworks/python3.framework/python3, 9): image not found
Native library (darwin-x86-64/libpython3.dylib) not found in resource path (/Users/XXX-userName/IdeaProjects/gstlib-master/target/scala-2.13/classes:/Users/XXX-userName/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/aggregator-nxrepository/me/shadaj/scalapy-core_2.13/0.5.2/scalapy-core_2.13-0.5.2.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/aggregator-nxrepository/me/shadaj/scalapy-macros_2.13/0.5.2/scalapy-macros_2.13-0.5.2.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/central-cache/net/java/dev/jna/jna/5.11.0/jna-5.11.0.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/central-cache/org/json4s/json4s-ast_2.13/3.6.10/json4s-ast_2.13-3.6.10.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/central-cache/org/json4s/json4s-core_2.13/3.6.10/json4s-core_2.13-3.6.10.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/central-cache/org/json4s/json4s-native_2.13/3.6.10/json4s-native_2.13-3.6.10.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/central-cache/org/json4s/json4s-scalap_2.13/3.6.10/json4s-scalap_2.13-3.6.10.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/central-cache/org/scala-lang/modules/scala-collection-compat_2.13/2.5.0/scala-collection-compat_2.13-2.5.0.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.1/scala-library-2.13.1.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.1/scala-reflect-2.13.1.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.Native.register(Native.java:1774)
	at com.sun.jna.Native.register(Native.java:1493)
	at me.shadaj.scalapy.interpreter.CPythonAPIInterface.$anonfun$loadAttempts$2(CPythonAPI.scala:18)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.Try$.apply(Try.scala:210)
	at me.shadaj.scalapy.interpreter.CPythonAPIInterface.$anonfun$loadAttempts$1(CPythonAPI.scala:18)
	at scala.collection.immutable.Stream.map(Stream.scala:175)
	at me.shadaj.scalapy.interpreter.CPythonAPIInterface.<init>(CPythonAPI.scala:18)
	at me.shadaj.scalapy.interpreter.CPythonAPI$.<init>(CPythonAPI.scala:112)
	at me.shadaj.scalapy.interpreter.CPythonAPI$.<clinit>(CPythonAPI.scala:112)
	at me.shadaj.scalapy.interpreter.CPythonInterpreter$.$anonfun$initialize$2(CPythonInterpreter.scala:15)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.Option.fold(Option.scala:263)
	at me.shadaj.scalapy.interpreter.CPythonInterpreter$.initialize(CPythonInterpreter.scala:15)
	at me.shadaj.scalapy.interpreter.CPythonInterpreter$.<clinit>(CPythonInterpreter.scala:21)
	at me.shadaj.scalapy.py.package$.<clinit>(package.scala:17)
	at gstlib.PythonTest$.main(PythonTest.scala:7)
	at gstlib.PythonTest.main(PythonTest.scala)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libpython3.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 19 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libpython3.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 19 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/XXX-userName/Library/Frameworks/python3.framework/python3, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
		... 19 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/python3.framework/python3, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
		... 19 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/python3.framework/python3, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
		... 19 more
	Suppressed: java.io.IOException: Native library (darwin-x86-64/libpython3.dylib) not found in resource path (/Users/XXX-userName/IdeaProjects/gstlib-master/target/scala-2.13/classes:/Users/XXX-userName/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/aggregator-nxrepository/me/shadaj/scalapy-core_2.13/0.5.2/scalapy-core_2.13-0.5.2.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/aggregator-nxrepository/me/shadaj/scalapy-macros_2.13/0.5.2/scalapy-macros_2.13-0.5.2.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/central-cache/net/java/dev/jna/jna/5.11.0/jna-5.11.0.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/central-cache/org/json4s/json4s-ast_2.13/3.6.10/json4s-ast_2.13-3.6.10.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/central-cache/org/json4s/json4s-core_2.13/3.6.10/json4s-core_2.13-3.6.10.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/central-cache/org/json4s/json4s-native_2.13/3.6.10/json4s-native_2.13-3.6.10.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/central-cache/org/json4s/json4s-scalap_2.13/3.6.10/json4s-scalap_2.13-3.6.10.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/artifactory.qa.XXX-Companry-name.com/artifactory/central-cache/org/scala-lang/modules/scala-collection-compat_2.13/2.5.0/scala-collection-compat_2.13-2.5.0.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.1/scala-library-2.13.1.jar:/Users/XXX-userName/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.1/scala-reflect-2.13.1.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1145)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
		... 19 more

**Comment by kiendang** [comment]
You would have to pass the path to `python`, not the directory where it's located. Could you try again with
```scala
val python1 = ai.kien.python.Python("/Users/XXX-userName/opt/anaconda3/envs/self_test/bin/python")
```

**Comment by LizzyMiao** [comment]
> You would have to pass the path to `python`, not the directory where it's located. Could you try again with
> 
> ```scala
> val python1 = ai.kien.python.Python("/Users/XXX-userName/opt/anaconda3/envs/self_test/bin/python")
> ```

it's a typo, sorry about this

**Comment by LizzyMiao** [comment]
One thing I notice is that I go to /Users/XXX-userName/Library/Frameworks folder, there is a Python.framework folder which holds all 2.XXX version of python... 
I do have several different version of python installed in my machine, and the code seems ignore the one that I point out in python1 and seems to want to use system defined python

**Comment by kiendang** [comment]
Could be due to the regression introduced in #270 that was fixed in #304. Could you try ScalaPy 0.5.3 instead?
```scala
libraryDependencies += "dev.scalapy" %% "scalapy-core" % "0.5.3"
```

**Comment by LizzyMiao** [comment]
> Could be due to the regression introduced in #270 that was fixed in #304. Could you try ScalaPy 0.5.3 instead?
> 
> ```scala
> libraryDependencies += "dev.scalapy" %% "scalapy-core" % "0.5.3"
> ```

same, I think there might be something wrong with my system config....

java.lang.UnsatisfiedLinkError: Unable to load library 'python3':
dlopen(libpython3.dylib, 9): image not found
dlopen(libpython3.dylib, 9): image not found
dlopen(/Users/XXX/Library/Frameworks/python3.framework/python3, 9): image not found
dlopen(/Library/Frameworks/python3.framework/python3, 9): image not found
dlopen(/System/Library/Frameworks/python3.framework/python3, 9): image not found
Native library (darwin-x86-64/libpython3.dylib) not found in resource path (/Users/XXX/IdeaProjects/gstlib-master/target/scala-2.13/classes:/Users/XXX/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/aggregator-nxrepository/dev/scalapy/scalapy-core_2.13/0.5.3/scalapy-core_2.13-0.5.3.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/aggregator-nxrepository/dev/scalapy/scalapy-macros_2.13/0.5.3/scalapy-macros_2.13-0.5.3.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/central-cache/net/java/dev/jna/jna/5.11.0/jna-5.11.0.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/central-cache/org/json4s/json4s-ast_2.13/3.6.10/json4s-ast_2.13-3.6.10.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/central-cache/org/json4s/json4s-core_2.13/3.6.10/json4s-core_2.13-3.6.10.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/central-cache/org/json4s/json4s-native_2.13/3.6.10/json4s-native_2.13-3.6.10.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/central-cache/org/json4s/json4s-scalap_2.13/3.6.10/json4s-scalap_2.13-3.6.10.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/central-cache/org/scala-lang/modules/scala-collection-compat_2.13/2.8.1/scala-collection-compat_2.13-2.8.1.jar:/Users/XXX/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.1/scala-library-2.13.1.jar:/Users/XXX/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.1/scala-reflect-2.13.1.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.Native.register(Native.java:1774)
	at com.sun.jna.Native.register(Native.java:1493)
	at me.shadaj.scalapy.interpreter.CPythonAPIInterface.$anonfun$loadAttempts$1(CPythonAPI.scala:20)
	at scala.collection.immutable.Stream.map(Stream.scala:175)
	at me.shadaj.scalapy.interpreter.CPythonAPIInterface.<init>(CPythonAPI.scala:19)
	at me.shadaj.scalapy.interpreter.CPythonAPI$.<init>(CPythonAPI.scala:119)
	at me.shadaj.scalapy.interpreter.CPythonAPI$.<clinit>(CPythonAPI.scala:119)
	at me.shadaj.scalapy.interpreter.CPythonInterpreter$.$anonfun$initialize$2(CPythonInterpreter.scala:16)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.Option.fold(Option.scala:263)
	at me.shadaj.scalapy.interpreter.CPythonInterpreter$.initialize(CPythonInterpreter.scala:16)
	at me.shadaj.scalapy.interpreter.CPythonInterpreter$.<clinit>(CPythonInterpreter.scala:22)
	at me.shadaj.scalapy.py.package$.<clinit>(package.scala:17)
	at gstlib.PythonTest$.main(PythonTest.scala:7)
	at gstlib.PythonTest.main(PythonTest.scala)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libpython3.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 16 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libpython3.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 16 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/XXX/Library/Frameworks/python3.framework/python3, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
		... 16 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/python3.framework/python3, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
		... 16 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/python3.framework/python3, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
		... 16 more
	Suppressed: java.io.IOException: Native library (darwin-x86-64/libpython3.dylib) not found in resource path (/Users/XXX/IdeaProjects/gstlib-master/target/scala-2.13/classes:/Users/XXX/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/aggregator-nxrepository/dev/scalapy/scalapy-core_2.13/0.5.3/scalapy-core_2.13-0.5.3.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/aggregator-nxrepository/dev/scalapy/scalapy-macros_2.13/0.5.3/scalapy-macros_2.13-0.5.3.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/central-cache/net/java/dev/jna/jna/5.11.0/jna-5.11.0.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/central-cache/org/json4s/json4s-ast_2.13/3.6.10/json4s-ast_2.13-3.6.10.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/central-cache/org/json4s/json4s-core_2.13/3.6.10/json4s-core_2.13-3.6.10.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/central-cache/org/json4s/json4s-native_2.13/3.6.10/json4s-native_2.13-3.6.10.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/central-cache/org/json4s/json4s-scalap_2.13/3.6.10/json4s-scalap_2.13-3.6.10.jar:/Users/XXX/Library/Caches/Coursier/v1/https/artifactory.qa.company.com/artifactory/central-cache/org/scala-lang/modules/scala-collection-compat_2.13/2.8.1/scala-collection-compat_2.13-2.8.1.jar:/Users/XXX/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.1/scala-library-2.13.1.jar:/Users/XXX/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.1/scala-reflect-2.13.1.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1145)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
		... 16 more
java.lang.UnsatisfiedLinkError: Unable to load library 'python3.10':
dlopen(libpython3.10.dylib, 9): image not found
dlopen(libpython3.10.dylib, 9): image not found

**Comment by kiendang** [comment]
for debugging purpose could you run a main method like this?

```scala
object PythonTest {
  def main(args: Array[String]): Unit = {
    List("jna.library.path", "scalapy.python.library", "scalapy.python.programname").foreach(prop =>
      println(prop, System.getProperty(prop))
    )
  }
}
```

**Comment by kiendang** [comment]
Also another way to use ScalaPy is to setup inside your main method instead of sbt.
In sbt you would add both scalapy and python-native-libs as dependency

```scala
libraryDependencies ++= Seq(
  "dev.scalay" %% "scalapy-core" % "0.5.3",
  "ai.kien" %% "python-native-libs" % "0.2.4"
)
```

without all that `javaOpts`

then inside your main method

```scala
import me.shadaj.scalapy.py
import me.shadaj.scalapy.py.SeqConverters

object PythonTest {
  def main(args: Array[String]): Unit = {
    ai.kien.python.Python("</path/to/python>").scalapyProperties.fold(
      ex => println(s"Error while getting ScalaPy properties: $ex"),
      props => props.foreach { case(k, v) => System.setProperty(k, v) }
    )

    val mypy = py.module("mypy")
    print("hello")
  }
}

```

**Comment by LizzyMiao** [comment]
> ```scala
> def main(args: Array[String]): Unit = {
>     List("jna.library.path", "scalapy.python.library", "scalapy.python.programname").foreach(prop =>
>       println(prop, System.getProperty(prop))
>     )
>   }
> ```
None of the lib path is set, I think something is missing in my build.sbt ...
(jna.library.path,null)
(scalapy.python.library,null)
(scalapy.python.programname,null)

**Comment by LizzyMiao** [comment]
> ```scala
> /Users/XXX-userName/opt/anaconda3/envs/self_test/bin/python
> ```

I changed code into `val mypy = py.module("hnswlib")` cause I do installed hnswlib module in my self_test anaconda env, mypy is a not recognized module... and it worked!!!
One more question, how does this integrated with spark scala? spark executor just use the python path installed in that machine?

**Comment by kiendang** [comment]
It should work but needs some setup. I'm not exactly sure how though. You can dig into VirtusLab/scala-cli#1597.

**Comment by LizzyMiao** [comment]
> It should work but needs some setup. I'm not exactly sure how though. You can dig into [VirtusLab/scala-cli#1594](https://github.com/VirtusLab/scala-cli/pull/1594).

got it, thank you!

**Comment by mullerhai** [comment]
meet same  error ,  from  error  
we  need know  where is the [resource path] defined ??
```

java.lang.UnsatisfiedLinkError: Unable to load library 'python3':
The specified module could not be found.

The specified module could not be found.

The specified module could not be found.

Native library (win32-x86-64/python3.dll) not found in resource path (D:\data\git\storch-scalapy\target\scala-3.6.4\classes;C:\Users\hai71\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\dev\scalapy\scalapy-macros_3\0.5.3%2B14-95e6ab08\scalapy-macros_3-0.5.3%2B14-95e6ab08.jar;C:\Users\hai71\AppData\Local\Coursier\cache\v1\https\maven.aliyun.com\repository\public\dev\scalapy\scalapy-core_3\0.5.3%2B14-95e6ab08\scalapy-core_3-0.5.3%2B14-95e6ab08.jar;C:\Users\hai71\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.15\scala-library-2.13.15.jar;C:\Users\hai71\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\net\java\dev\jna\jna\5.11.0\jna-5.11.0.jar;C:\Users\hai71\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\bytedeco\javacpp\1.5.4\javacpp-1.5.4-windows-x86_64.jar;C:\Users\hai71\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\bytedeco\javacpp\1.5.4\javacpp-1.5.4.jar;C:\Users\hai71\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala3-library_3\3.6.4\scala3-library_3-3.6.4.jar;C:\Users\hai71\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\modules\scala-collection-compat_3\2.12.0\scala-collection-compat_3-2.12.0.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)

```
